#!/usr/bin/env bash
# Generated by VURA: Export CLI Credential Bootstrap
#
# Imports non-secret connection profile shape into the vura-runner CLI's local
# stores: `vura-runner credentials add` for SQL/Azure SQL profiles, and
# `vura-runner connections add` for every other connector kind (Dataverse,
# SharePoint, OneDrive, Google Drive, S3, local, ...). Every profile below is
# added with a placeholder secret (--secret "") — fill in real values with
# set-vura-secrets.sh before running a notebook that needs them.
#
# You may need to make this script executable: chmod +x vura-import-profiles.sh
set -e

vura-runner credentials add 'local-sql-server-0681' 'localhost' 'D365MockDB' 'SqlLogin' --username 'sa' --port '1433' --secret ''
vura-runner credentials add 'sql-353408' 'org7dc37214.crm17.dynamics.com' 'unqccfe9ebc35b1f111aaa06045bd2b6' 'ServicePrincipal' --client-id 'bac50144-5e82-46ce-954b-1f1de88271bc' --tenant-id '900dcf37-9e26-4a64-9071-567736241b13' --port '1433' --secret ''
vura-runner connections add 'sql-429367' 'dataverse' --field 'environmentUrl=https://org7dc37214.crm17.dynamics.com' --field 'tenantId=900dcf37-9e26-4a64-9071-567736241b13' --field 'clientId=bac50144-5e82-46ce-954b-1f1de88271bc' --secret ''
